### ISSUE TITLE
노트 내용 수정

### ISSUE THREAD

**Issue by changicho** [woowa-techcamp-2020/todo-1#11]
- [x] 노트 더블클릭하면 수정 모달창 띄움
- 노트 내용 수정 모달창
    - [x] 입력창에서 할 일(note)을 수정할 수 있다.
    - [x] 입력창은 우측하단에 그립을 잡아서 세로로 늘릴 수 있다.
    - [x] 글자 수 제한은 500자이다.
    - [x] 입력창에서 모든 내용을 지우면 Save note 버튼은 비활성화된다.
    - [x] Save note를 누르면 모달 레이어는 사라지고, 할 일 카드에 수정한 내용이 반영된다.
    - [x] x 버튼에 마우스 hover 하면 x 버튼의 색상이 변경된다.
    - [x] x 버튼을 누르면 2번 레이어는 사라지고, 변경 내용은 반영되지 않고 그냥 취소된다.

**Comment by wudys** [comment]
DOM 객체 리페인트 안되는 버그 발견

**Comment by wudys** [comment]
#64
