### ISSUE TITLE
모달 관리자

### ISSUE THREAD

**Issue by changicho** [woowa-techcamp-2020/todo-1#26]
- [x] 보여주기 숨기기
- [x] 모달을 열 때 어떤 모달을 보여줄 지 분기 처리
- [x] X버튼과 ESC 키를 누를 경우, 모달이 닫힘

**Comment by wudys** [comment]
"모달을 열 때 어떤 모달을 보여줄 지 분기 처리" 대신 직접 사용할 모달을 호출하는 방식을 채용함
